name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t1-1
      id: t1-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t1-1
        setup-command: gcc ./code/1-1.c -o a
        command: "./a ./code/myfile.txt"
        input: " "
        expected-output: "The sun rose slowly over the distant mountains, \n\n"
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: t1-2
      id: t1-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t1-2
        setup-command: gcc ./code/1-2.c -o ./a
        command: "./a ./code/myfile.txt ./code/myfile2.txt"
        input: ''
        expected-output: "The sun rose slowly over the distant mountains, \n\nThe
          road ahead curved gently to the left and disappeared into a dense forest.
          \n\n"
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1-1_RESULTS: "${{steps.t1-1.outputs.result}}"
        T1-2_RESULTS: "${{steps.t1-2.outputs.result}}"
      with:
        runners: t1-1,t1-2
